language: en_US
offline-mode: false
enable-geyser: true
enable-yggdrasil: true
custom-api-ahead: false
custom-apis:
#  - https://example.com/api/yggdrasil
mineskin-visibility: unlisted
debug-mode: false